
compile:
	gcc -Wall mmap-argument.c -o mmap-argument
	gcc -Wall memfdcreate-argument.c -o memfdcreate-argument
	gcc -Wall fcntl-argument.c -o fcntl-argument

clean:
	rm *.o
	rm mmap-argument memfdcreate-argument fcntl-argument
